/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as WalletImport } from './routes/wallet'
import { Route as TransactImport } from './routes/transact'
import { Route as SettingsImport } from './routes/settings'
import { Route as OnboardingImport } from './routes/onboarding'
import { Route as InboxImport } from './routes/inbox'
import { Route as AccountImport } from './routes/account'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const WalletRoute = WalletImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRoute,
} as any)

const TransactRoute = TransactImport.update({
  id: '/transact',
  path: '/transact',
  getParentRoute: () => rootRoute,
} as any)

const SettingsRoute = SettingsImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRoute,
} as any)

const OnboardingRoute = OnboardingImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRoute,
} as any)

const InboxRoute = InboxImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRoute,
} as any)

const AccountRoute = AccountImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountImport
      parentRoute: typeof rootRoute
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxImport
      parentRoute: typeof rootRoute
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingImport
      parentRoute: typeof rootRoute
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsImport
      parentRoute: typeof rootRoute
    }
    '/transact': {
      id: '/transact'
      path: '/transact'
      fullPath: '/transact'
      preLoaderRoute: typeof TransactImport
      parentRoute: typeof rootRoute
    }
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/inbox': typeof InboxRoute
  '/onboarding': typeof OnboardingRoute
  '/settings': typeof SettingsRoute
  '/transact': typeof TransactRoute
  '/wallet': typeof WalletRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/inbox': typeof InboxRoute
  '/onboarding': typeof OnboardingRoute
  '/settings': typeof SettingsRoute
  '/transact': typeof TransactRoute
  '/wallet': typeof WalletRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/inbox': typeof InboxRoute
  '/onboarding': typeof OnboardingRoute
  '/settings': typeof SettingsRoute
  '/transact': typeof TransactRoute
  '/wallet': typeof WalletRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/inbox'
    | '/onboarding'
    | '/settings'
    | '/transact'
    | '/wallet'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/account'
    | '/inbox'
    | '/onboarding'
    | '/settings'
    | '/transact'
    | '/wallet'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account'
    | '/inbox'
    | '/onboarding'
    | '/settings'
    | '/transact'
    | '/wallet'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRoute
  InboxRoute: typeof InboxRoute
  OnboardingRoute: typeof OnboardingRoute
  SettingsRoute: typeof SettingsRoute
  TransactRoute: typeof TransactRoute
  WalletRoute: typeof WalletRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRoute,
  InboxRoute: InboxRoute,
  OnboardingRoute: OnboardingRoute,
  SettingsRoute: SettingsRoute,
  TransactRoute: TransactRoute,
  WalletRoute: WalletRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/account",
        "/inbox",
        "/onboarding",
        "/settings",
        "/transact",
        "/wallet"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/account": {
      "filePath": "account.tsx"
    },
    "/inbox": {
      "filePath": "inbox.tsx"
    },
    "/onboarding": {
      "filePath": "onboarding.tsx"
    },
    "/settings": {
      "filePath": "settings.tsx"
    },
    "/transact": {
      "filePath": "transact.tsx"
    },
    "/wallet": {
      "filePath": "wallet.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
